flash:
	rm -f /Volumes/CIRCUITPY/main.py
	cp example.py /Volumes/CIRCUITPY/main.py
	rm -f /Volumes/CIRCUITPY/lib/APDS9960-circuitpython.py
	cp APDS9960-circuitpython.py /Volumes/CIRCUITPY/lib/APDS9960-circuitpy.py

clean: 
	rm -f /Volumes/CIRCUITPY/main.py
	rm -f /Volumes/CIRCUITPY/lib/APDS9960-circuitpython.py
